### ISSUE TITLE
How use ChangesetForm with template imports?

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/frontile#327]
- Other components like [Button](https://frontile.dev/docs/buttons/button) have a section in documentation called `Import` so I can just grab: `import { Button } from '@frontile/buttons';`
- But for [ChangesetForm](https://frontile.dev/docs/changeset-form/usage) this is not the case. How do I use it in `gjs/gts`?
  - How do I import `ChangesetForm`?
  - How do I import `changeset` (the helper)? Technically not really the issue of this addon, but would make people's life easier.

**Comment by MichalBryxi** [comment]
I'm more than happy to spawn a PR that would improve the documentation, but I'm writing this after 30+ minutes trying various options, grepping for examples and I'm at a loss, so will need a pointer to an actual example.

**Comment by josemarluedke** [comment]
I believe the published version can be imported using this:

```ts
import ChangesetFrom from '@frontile/changeset-form/components/changeset-form';
```


Please note that I plan to deprecate this pkg after I release a stable version of everything. I mention in a todo list here: https://github.com/josemarluedke/frontile/issues/289

We still use this package, so it's not like I will drop it right now. However, I plan to deprecate it after at least stable version 0.17 is released. It should be removed before v1, together with legacy-forms pkg.

This is because Ember Changeset is not where I would like to see it. We had so many issues with it over time that we plan to use something like https://zod.dev/ instead.

**Comment by josemarluedke** [comment]
There is no directly replacement, however, you can use the `@frontile/froms` pkg for basic forms functionality. Unsure if we would create a pkg to integrate with Zod, most likely not.

**Comment by MichalBryxi** [comment]
Thanks for your answer and your hints.

Somehow I missed the label "deprecated" next to `ChangesetForm` 🤦🏾  My other projects already use `Form` 🤷🏾
